Created orderController base tested with postman
piotr-grosicki/project-jdp-2401-01 pull request #1
Opened 2024-01-27 14:22 UTC by TheBlackPandaa

2024-01-28 07:17 UTC, piotr-grosicki requested changes

2024-01-28 07:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Order/OrderController.java
> +public class OrderController {
brakuje jakiegos sztucznego DTO zeby moc to latwo przetestowac w postmanie

2024-01-30 09:13 UTC, TheBlackPandaa commented on src/main/java/com/kodilla/ecommercee/Order/OrderController.java
> +public class OrderController {
Dodałem DTO

2024-01-30 17:48 UTC, piotr-grosicki requested changes

2024-01-30 17:48 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Order/OrderController.java
> +    public OrderTestDTO updateOrder(){
no ale jeszcze wykorzystaj te DTO :P

2024-01-31 14:59 UTC, merged