ProductController created
piotr-grosicki/project-jdp-2401-01 pull request #2
Opened 2024-01-28 11:35 UTC by Gwynnbleidd11

ProductController was created along with basic domain classes. I had to comment `application.properties` in order to test if application runs fine. Forgot to un-comment it before push, not sure how to change it now. Please reject if needed and I will correct.

2024-01-28 12:11 UTC, piotr-grosicki commented
Just commit and push next changes to the same branch :)

2024-01-28 14:12 UTC, Gwynnbleidd11 commented
Next commit done. Application.properties file corrected and UserController created. Please review

2024-01-28 18:50 UTC, piotr-grosicki requested changes
remove everything related to User

2024-01-28 18:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void createProduct(final ProductDto productDto) {
missing RequestBody

2024-01-28 18:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public ProductDto updateProduct(final ProductDto productDto) {
missing RequestBody

2024-01-28 18:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/controller/ProductController.java
> +    public void deleteProduct(final Long productId) {
missing RequestParam / PathVariable

2024-01-28 18:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/product/domain/Product.java
> +public class Product {
entity is not needed right now

2024-01-28 18:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +public class UserController {
why user controller is created on this branch?

2024-01-29 07:50 UTC, Gwynnbleidd11 commented
ProductController corrected, everything related to user removed from this branch. I added User to this branch, as this is how I understood your comment "Just commit and push next changes to the same branch :)". I wasn't expecting any changes to ProductController branch at this stage.

2024-01-30 17:49 UTC, merged