Jdp240101 24 order controller
piotr-grosicki/project-jdp-2401-01 pull request #24
Opened 2024-02-14 18:41 UTC by TheBlackPandaa

2024-02-15 11:53 UTC, Gwynnbleidd11 requested changes

2024-02-15 11:53 UTC, Gwynnbleidd11 commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +    public ResponseEntity<OrderDto> getOrder(@PathVariable int orderId) throws OrderNotFoundException{
orderId powinno być typu Long, tak jak w metodzie delete

2024-02-15 11:53 UTC, Gwynnbleidd11 commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +        return ResponseEntity.ok().build();
metoda deklete nie powinna nic próbować zbudować `return ResponseEntity.noContent().build();`

2024-02-15 11:53 UTC, Gwynnbleidd11 commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +public class  UserController {
po co ta dodatkowa spacja przed UserController?

2024-02-16 10:37 UTC, TheBlackPandaa commented on src/main/java/com/kodilla/ecommercee/order/controller/OrderController.java
> +        return ResponseEntity.ok().build();
używaliśmy w tasku ok().build() i tym się sugerowałem, nie jestem pewien co do różnicy więc nie wiem czemu mielibyśmy robić no content teraz

2024-02-16 11:49 UTC, Gwynnbleidd11 approved these changes

2024-02-16 11:49 UTC, merged